language: php

php: 
  - 5.3
  - 5.4

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev

script: 
  - phpunit
  - php artisan generate:scaffold post --fields="title:string, body:text, count:integer"